//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_agence_mysql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cao_salario
    {
        public string co_usuario { get; set; }
        public System.DateTime dt_alteracao { get; set; }
        public float brut_salario { get; set; }
        public float liq_salario { get; set; }
    }
}
