//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_agence_mysql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cao_usuario
    {
        public string co_usuario { get; set; }
        public string no_usuario { get; set; }
        public string ds_senha { get; set; }
        public string co_usuario_autorizacao { get; set; }
        public Nullable<decimal> nu_matricula { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public Nullable<System.DateTime> dt_admissao_empresa { get; set; }
        public Nullable<System.DateTime> dt_desligamento { get; set; }
        public Nullable<System.DateTime> dt_inclusao { get; set; }
        public Nullable<System.DateTime> dt_expiracao { get; set; }
        public string nu_cpf { get; set; }
        public string nu_rg { get; set; }
        public string no_orgao_emissor { get; set; }
        public string uf_orgao_emissor { get; set; }
        public string ds_endereco { get; set; }
        public string no_email { get; set; }
        public string no_email_pessoal { get; set; }
        public string nu_telefone { get; set; }
        public System.DateTime dt_alteracao { get; set; }
        public string url_foto { get; set; }
        public string instant_messenger { get; set; }
        public Nullable<long> icq { get; set; }
        public string msn { get; set; }
        public string yms { get; set; }
        public string ds_comp_end { get; set; }
        public string ds_bairro { get; set; }
        public string nu_cep { get; set; }
        public string no_cidade { get; set; }
        public string uf_cidade { get; set; }
        public Nullable<System.DateTime> dt_expedicao { get; set; }
    }
}
