//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_agence_mysql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cao_fatura
    {
        public long co_fatura { get; set; }
        public int co_cliente { get; set; }
        public int co_sistema { get; set; }
        public int co_os { get; set; }
        public int num_nf { get; set; }
        public float total { get; set; }
        public float valor { get; set; }
        public System.DateTime data_emissao { get; set; }
        public string corpo_nf { get; set; }
        public float comissao_cn { get; set; }
        public float total_imp_inc { get; set; }
    }
}
