//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_agence_mysql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissao_sistema
    {
        public string co_usuario { get; set; }
        public decimal co_tipo_usuario { get; set; }
        public decimal co_sistema { get; set; }
        public string in_ativo { get; set; }
        public string co_usuario_atualizacao { get; set; }
        public System.DateTime dt_atualizacao { get; set; }
    }
}
